// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QRB.Data;

#nullable disable

namespace QRB.Migrations
{
    [DbContext(typeof(QRBDbContext))]
    [Migration("20250819145841_TestVoucherModel")]
    partial class TestVoucherModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguoiDungQuyenSuDung", b =>
                {
                    b.Property<Guid>("NguoiDungsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuyenSuDungsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NguoiDungsID", "QuyenSuDungsID");

                    b.HasIndex("QuyenSuDungsID");

                    b.ToTable("NguoiDungQuyenSuDung");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("QRB.Models.ChiNhanh", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ChiNhanh");

                    b.HasData(
                        new
                        {
                            ID = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(497),
                            IsDelete = false,
                            MaChiNhanh = "QRB001",
                            TenChiNhanh = "QRB Coffee - Chi nhánh chính"
                        });
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonDeXuat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDDeXuatMuaSam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NguyenLieuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDDeXuatMuaSam");

                    b.HasIndex("IDNguyenLieu");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("ChiTietDonDeXuat");
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IDDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDLoaiSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThanhTien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDDonHang");

                    b.HasIndex("IDLoaiSanPham");

                    b.HasIndex("IDSanPham");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("QRB.Models.Customer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GiaTriDonHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("QRB.Models.CustomerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiaTriDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CustomerInfo");
                });

            modelBuilder.Entity("QRB.Models.DeXuatMuaSam", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("AcceptTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDChiNhanhGui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDChiNhanhNhan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNguoiGui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNguoiNhan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaDeXuat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiDungDeXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReceiveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RejectTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanhGui");

                    b.HasIndex("IDChiNhanhNhan");

                    b.HasIndex("IDNguoiGui");

                    b.HasIndex("IDNguoiNhan");

                    b.HasIndex("MaDeXuat")
                        .IsUnique();

                    b.ToTable("DeXuatMuaSam");
                });

            modelBuilder.Entity("QRB.Models.Department", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.ToTable("Department");
                });

            modelBuilder.Entity("QRB.Models.DonHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DaTraDon")
                        .HasColumnType("bit");

                    b.Property<string>("DonGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaUuDai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoBan")
                        .HasColumnType("int");

                    b.Property<string>("TienUuDai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TongTien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("QRB.Models.Ingredient", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IngredientCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IngredientCode")
                        .IsUnique();

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("QRB.Models.KhachHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiaTriDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QRB.Models.KhoSanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NguyenLieuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoLuongConLai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IDNguyenLieu");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("KhoSanPham");
                });

            modelBuilder.Entity("QRB.Models.LoaiSanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IDSanPham");

                    b.HasIndex("MaLoai")
                        .IsUnique();

                    b.ToTable("LoaiSanPham");

                    b.HasData(
                        new
                        {
                            ID = new Guid("af0a1d29-0c29-4e81-a473-3bb2747be8cb"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(637),
                            DonGia = "25000",
                            IDChiNhanh = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            IDSanPham = new Guid("cb9f1998-32ae-4841-8c30-191fb54e0fbd"),
                            IsDelete = false,
                            MaLoai = "CFD001",
                            TenLoai = "Cà phê đen"
                        },
                        new
                        {
                            ID = new Guid("3d4b80ae-d7f7-4433-90a0-10ad44bbdc5c"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(662),
                            DonGia = "30000",
                            IDChiNhanh = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            IDSanPham = new Guid("cb9f1998-32ae-4841-8c30-191fb54e0fbd"),
                            IsDelete = false,
                            MaLoai = "CFS001",
                            TenLoai = "Cà phê sữa"
                        },
                        new
                        {
                            ID = new Guid("c3000f64-68ca-4002-a409-408e0d3e7bda"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(664),
                            DonGia = "35000",
                            IDChiNhanh = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            IDSanPham = new Guid("16cf86f7-9a78-4878-bdc4-e852863ee46e"),
                            IsDelete = false,
                            MaLoai = "TS001",
                            TenLoai = "Trà sữa"
                        },
                        new
                        {
                            ID = new Guid("84d38c23-1430-426a-9e3c-4bf1f3e407ed"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(677),
                            DonGia = "40000",
                            IDChiNhanh = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            IDSanPham = new Guid("01ac0027-8632-44e6-b940-a22774f31186"),
                            IsDelete = false,
                            MaLoai = "BC001",
                            TenLoai = "Bánh croissant"
                        });
                });

            modelBuilder.Entity("QRB.Models.MaUuDai", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KhachHangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TienGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiSuDung")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("KhachHangID");

                    b.ToTable("MaUuDai");
                });

            modelBuilder.Entity("QRB.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Staff");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("TenNguoiDung")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("QRB.Models.NguyenLieu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("QRB.Models.NhomSanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("NhomSanPham", (string)null);
                });

            modelBuilder.Entity("QRB.Models.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IDCustomer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDDepartment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDEmployee")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Served")
                        .HasColumnType("bit");

                    b.Property<int?>("Table")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VoucherPrice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("IDCustomer");

                    b.HasIndex("IDDepartment");

                    b.HasIndex("IDEmployee");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("QRB.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDProduct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDProductType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDTypeProduct");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Amount");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDOrder");

                    b.HasIndex("IDProduct");

                    b.HasIndex("IDProductType");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("QRB.Models.QuyenSuDung", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MaQuyen")
                        .IsUnique();

                    b.ToTable("QuyenSuDung");
                });

            modelBuilder.Entity("QRB.Models.SanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhomSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IdNhomSanPham");

                    b.HasIndex("MaSanPham")
                        .IsUnique();

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            ID = new Guid("cb9f1998-32ae-4841-8c30-191fb54e0fbd"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(608),
                            IDChiNhanh = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            IdNhomSanPham = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDelete = false,
                            MaSanPham = "CF001",
                            TenSanPham = "Cà phê"
                        },
                        new
                        {
                            ID = new Guid("16cf86f7-9a78-4878-bdc4-e852863ee46e"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(610),
                            IDChiNhanh = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            IdNhomSanPham = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDelete = false,
                            MaSanPham = "TR001",
                            TenSanPham = "Trà"
                        },
                        new
                        {
                            ID = new Guid("01ac0027-8632-44e6-b940-a22774f31186"),
                            CreateTime = new DateTime(2025, 8, 19, 21, 58, 41, 176, DateTimeKind.Local).AddTicks(612),
                            IDChiNhanh = new Guid("07e4a3b8-5366-4c54-a2e0-c3373ab41ae6"),
                            IdNhomSanPham = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDelete = false,
                            MaSanPham = "BN001",
                            TenSanPham = "Bánh ngọt"
                        });
                });

            modelBuilder.Entity("QRB.Models.UserBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UK_UserBranches_UserId_BranchId");

                    b.ToTable("UserBranches");
                });

            modelBuilder.Entity("QRB.Models.Voucher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Discount");

                    b.Property<Guid>("IDCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDCustomer");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IsDelete");

                    b.Property<Guid?>("KhachHangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("VoucherCode");

                    b.HasKey("ID");

                    b.HasIndex("IDCustomer");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("VoucherCode")
                        .IsUnique();

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("NguoiDungQuyenSuDung", b =>
                {
                    b.HasOne("QRB.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.QuyenSuDung", null)
                        .WithMany()
                        .HasForeignKey("QuyenSuDungsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRolePermission", b =>
                {
                    b.HasOne("QRB.Models.Authorization.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.Authorization.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonDeXuat", b =>
                {
                    b.HasOne("QRB.Models.DeXuatMuaSam", "DeXuatMuaSam")
                        .WithMany("ChiTietDonDeXuats")
                        .HasForeignKey("IDDeXuatMuaSam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.Ingredient", "Ingredient")
                        .WithMany("ChiTietDonDeXuats")
                        .HasForeignKey("IDNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguyenLieu", null)
                        .WithMany("ChiTietDonDeXuats")
                        .HasForeignKey("NguyenLieuID");

                    b.Navigation("DeXuatMuaSam");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QRB.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IDDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IDLoaiSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("LoaiSanPham");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QRB.Models.DeXuatMuaSam", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanhGui")
                        .WithMany()
                        .HasForeignKey("IDChiNhanhGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QRB.Models.Department", "ChiNhanhNhan")
                        .WithMany("DeXuatMuaSams")
                        .HasForeignKey("IDChiNhanhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguyenLieu", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("IDNguoiGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguyenLieu", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("IDNguoiNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiNhanhGui");

                    b.Navigation("ChiNhanhNhan");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("QRB.Models.DonHang", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("DonHangs")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("IDKhachHang");

                    b.HasOne("QRB.Models.NguoiDung", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QRB.Models.KhoSanPham", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("KhoSanPhams")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.Ingredient", "Ingredient")
                        .WithMany("KhoSanPhams")
                        .HasForeignKey("IDNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguyenLieu", null)
                        .WithMany("KhoSanPhams")
                        .HasForeignKey("NguyenLieuID");

                    b.Navigation("ChiNhanh");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("QRB.Models.LoaiSanPham", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.SanPham", "SanPham")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QRB.Models.MaUuDai", b =>
                {
                    b.HasOne("QRB.Models.CustomerInfo", "CustomerInfo")
                        .WithMany()
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.KhachHang", null)
                        .WithMany("MaUuDais")
                        .HasForeignKey("KhachHangID");

                    b.Navigation("CustomerInfo");
                });

            modelBuilder.Entity("QRB.Models.NguoiDung", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("QRB.Models.Order", b =>
                {
                    b.HasOne("QRB.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("IDCustomer");

                    b.HasOne("QRB.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("IDDepartment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguoiDung", "Employee")
                        .WithMany()
                        .HasForeignKey("IDEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QRB.Models.OrderDetail", b =>
                {
                    b.HasOne("QRB.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IDOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.SanPham", "Product")
                        .WithMany()
                        .HasForeignKey("IDProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.LoaiSanPham", "ProductType")
                        .WithMany()
                        .HasForeignKey("IDProductType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("QRB.Models.SanPham", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.NhomSanPham", "NhomSanPham")
                        .WithMany()
                        .HasForeignKey("IdNhomSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("NhomSanPham");
                });

            modelBuilder.Entity("QRB.Models.UserBranch", b =>
                {
                    b.HasOne("QRB.Models.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QRB.Models.Voucher", b =>
                {
                    b.HasOne("QRB.Models.Customer", "Customer")
                        .WithMany("Vouchers")
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.KhachHang", null)
                        .WithMany("Vouchers")
                        .HasForeignKey("KhachHangID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QRB.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("QRB.Models.DeXuatMuaSam", b =>
                {
                    b.Navigation("ChiTietDonDeXuats");
                });

            modelBuilder.Entity("QRB.Models.Department", b =>
                {
                    b.Navigation("DeXuatMuaSams");

                    b.Navigation("DonHangs");

                    b.Navigation("KhoSanPhams");

                    b.Navigation("LoaiSanPhams");

                    b.Navigation("NguoiDungs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QRB.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("QRB.Models.Ingredient", b =>
                {
                    b.Navigation("ChiTietDonDeXuats");

                    b.Navigation("KhoSanPhams");
                });

            modelBuilder.Entity("QRB.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("MaUuDais");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("QRB.Models.LoaiSanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("QRB.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("QRB.Models.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietDonDeXuats");

                    b.Navigation("KhoSanPhams");
                });

            modelBuilder.Entity("QRB.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("QRB.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LoaiSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
