// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QRB.Data;

#nullable disable

namespace QRB.Migrations
{
    [DbContext(typeof(QRBDbContext))]
    partial class QRBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguoiDungQuyenSuDung", b =>
                {
                    b.Property<Guid>("NguoiDungsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuyenSuDungsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NguoiDungsID", "QuyenSuDungsID");

                    b.HasIndex("QuyenSuDungsID");

                    b.ToTable("NguoiDungQuyenSuDung");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("QRB.Models.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("QRB.Models.ChiNhanh", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ChiNhanh");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5687),
                            IsDelete = false,
                            MaChiNhanh = "QRB001",
                            TenChiNhanh = "QRB Coffee - Chi nhánh chính"
                        });
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonDeXuat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDDeXuatMuaSam")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDRequest");

                    b.Property<Guid>("IDNguyenLieu")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNguyenLieu");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDDeXuatMuaSam");

                    b.ToTable("RequestDetail");
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IDDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDLoaiSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThanhTien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDDonHang");

                    b.HasIndex("IDLoaiSanPham");

                    b.HasIndex("IDSanPham");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("QRB.Models.Customer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GiaTriDonHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("QRB.Models.CustomerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiaTriDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CustomerInfo");
                });

            modelBuilder.Entity("QRB.Models.DeXuatMuaSam", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("AcceptTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDChiNhanhGui")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSenDDepartment");

                    b.Property<Guid>("IDChiNhanhNhan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDReceiveDepartment");

                    b.Property<Guid>("IDNguoiGui")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSender");

                    b.Property<Guid>("IDNguoiNhan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDReceiver");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaDeXuat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RequestCode");

                    b.Property<string>("NoiDungDeXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("NoiDungTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RejectTitle");

                    b.Property<DateTime?>("ReceiveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RejectTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanhGui");

                    b.HasIndex("IDChiNhanhNhan");

                    b.HasIndex("IDNguoiGui");

                    b.HasIndex("IDNguoiNhan");

                    b.HasIndex("MaDeXuat")
                        .IsUnique();

                    b.ToTable("Request");
                });

            modelBuilder.Entity("QRB.Models.Department", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.ToTable("Department");
                });

            modelBuilder.Entity("QRB.Models.DonHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DaTraDon")
                        .HasColumnType("bit");

                    b.Property<string>("DonGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaUuDai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoBan")
                        .HasColumnType("int");

                    b.Property<string>("TienUuDai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TongTien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IDNhanVien");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("QRB.Models.Ingredient", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IngredientCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IngredientCode")
                        .IsUnique();

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("QRB.Models.KhoSanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NguyenLieuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoLuongConLai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IDNguyenLieu");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("KhoSanPham");
                });

            modelBuilder.Entity("QRB.Models.LoaiSanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Price");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDDepartment");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDProduct");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TypeProductCode");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TypeProductName");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IDSanPham");

                    b.HasIndex("MaLoai")
                        .IsUnique();

                    b.ToTable("TypeProduct");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4e9fef51-45b4-4e8e-932a-c0269202e4bc"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5839),
                            DonGia = "25000",
                            IDChiNhanh = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            IDSanPham = new Guid("302c11c6-9b01-48fa-adb8-ae249c95198f"),
                            IsDelete = false,
                            MaLoai = "CFD001",
                            TenLoai = "Cà phê đen"
                        },
                        new
                        {
                            ID = new Guid("e3561186-5250-499f-9ed6-9c2184dd4dfe"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5842),
                            DonGia = "30000",
                            IDChiNhanh = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            IDSanPham = new Guid("302c11c6-9b01-48fa-adb8-ae249c95198f"),
                            IsDelete = false,
                            MaLoai = "CFS001",
                            TenLoai = "Cà phê sữa"
                        },
                        new
                        {
                            ID = new Guid("026b2bac-6578-46b3-b8e0-efce45bdcb43"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5844),
                            DonGia = "35000",
                            IDChiNhanh = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            IDSanPham = new Guid("897f6f94-7451-47b6-ac74-f6d289203a0d"),
                            IsDelete = false,
                            MaLoai = "TS001",
                            TenLoai = "Trà sữa"
                        },
                        new
                        {
                            ID = new Guid("3b5e947f-ba65-46bc-b22b-2aaaeb9a5369"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5846),
                            DonGia = "40000",
                            IDChiNhanh = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            IDSanPham = new Guid("a5395ab3-c888-4deb-97f1-499233770565"),
                            IsDelete = false,
                            MaLoai = "BC001",
                            TenLoai = "Bánh croissant"
                        });
                });

            modelBuilder.Entity("QRB.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDDepartment");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UserName");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Account");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Staff")
                        .HasColumnName("Role");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("TenNguoiDung")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("QRB.Models.NguyenLieu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("QRB.Models.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IDCustomer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDDepartment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDEmployee")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefundAmount")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("RefundApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Served")
                        .HasColumnType("bit");

                    b.Property<int?>("Table")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VoucherPrice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("IDCustomer");

                    b.HasIndex("IDDepartment");

                    b.HasIndex("IDEmployee");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("QRB.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDProduct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDProductType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDTypeProduct");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Amount");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDOrder");

                    b.HasIndex("IDProduct");

                    b.HasIndex("IDProductType");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("QRB.Models.QuyenSuDung", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MaQuyen")
                        .IsUnique();

                    b.ToTable("QuyenSuDung");
                });

            modelBuilder.Entity("QRB.Models.SanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Picture");

                    b.Property<Guid>("IDChiNhanh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDDepartment");

                    b.Property<Guid>("IdCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProductCode");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProductName");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDChiNhanh");

                    b.HasIndex("IdCategory");

                    b.HasIndex("MaSanPham")
                        .IsUnique();

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = new Guid("302c11c6-9b01-48fa-adb8-ae249c95198f"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5815),
                            IDChiNhanh = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            IdCategory = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDelete = false,
                            MaSanPham = "CF001",
                            TenSanPham = "Cà phê"
                        },
                        new
                        {
                            ID = new Guid("897f6f94-7451-47b6-ac74-f6d289203a0d"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5817),
                            IDChiNhanh = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            IdCategory = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDelete = false,
                            MaSanPham = "TR001",
                            TenSanPham = "Trà"
                        },
                        new
                        {
                            ID = new Guid("a5395ab3-c888-4deb-97f1-499233770565"),
                            CreateTime = new DateTime(2025, 9, 11, 0, 9, 18, 351, DateTimeKind.Local).AddTicks(5819),
                            IDChiNhanh = new Guid("3c43a4c8-6612-462b-9da0-dcdd47684e38"),
                            IdCategory = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDelete = false,
                            MaSanPham = "BN001",
                            TenSanPham = "Bánh ngọt"
                        });
                });

            modelBuilder.Entity("QRB.Models.UserBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UK_UserBranches_UserId_BranchId");

                    b.ToTable("UserBranches");
                });

            modelBuilder.Entity("QRB.Models.Voucher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Discount");

                    b.Property<Guid>("IDCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDCustomer");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IsDelete");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("VoucherCode");

                    b.HasKey("ID");

                    b.HasIndex("IDCustomer");

                    b.HasIndex("VoucherCode")
                        .IsUnique();

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("NguoiDungQuyenSuDung", b =>
                {
                    b.HasOne("QRB.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.QuyenSuDung", null)
                        .WithMany()
                        .HasForeignKey("QuyenSuDungsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRolePermission", b =>
                {
                    b.HasOne("QRB.Models.Authorization.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.Authorization.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonDeXuat", b =>
                {
                    b.HasOne("QRB.Models.DeXuatMuaSam", "DeXuatMuaSam")
                        .WithMany("ChiTietDonDeXuats")
                        .HasForeignKey("IDDeXuatMuaSam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeXuatMuaSam");
                });

            modelBuilder.Entity("QRB.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QRB.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IDDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IDLoaiSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("LoaiSanPham");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QRB.Models.DeXuatMuaSam", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanhGui")
                        .WithMany()
                        .HasForeignKey("IDChiNhanhGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QRB.Models.Department", "ChiNhanhNhan")
                        .WithMany("DeXuatMuaSams")
                        .HasForeignKey("IDChiNhanhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguyenLieu", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("IDNguoiGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguyenLieu", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("IDNguoiNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiNhanhGui");

                    b.Navigation("ChiNhanhNhan");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("QRB.Models.DonHang", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("DonHangs")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguoiDung", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QRB.Models.KhoSanPham", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("KhoSanPhams")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.Ingredient", "Ingredient")
                        .WithMany("KhoSanPhams")
                        .HasForeignKey("IDNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguyenLieu", null)
                        .WithMany("KhoSanPhams")
                        .HasForeignKey("NguyenLieuID");

                    b.Navigation("ChiNhanh");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("QRB.Models.LoaiSanPham", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.SanPham", "SanPham")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QRB.Models.NguoiDung", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("QRB.Models.Order", b =>
                {
                    b.HasOne("QRB.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("IDCustomer");

                    b.HasOne("QRB.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("IDDepartment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguoiDung", "Employee")
                        .WithMany()
                        .HasForeignKey("IDEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QRB.Models.OrderDetail", b =>
                {
                    b.HasOne("QRB.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IDOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.SanPham", "Product")
                        .WithMany()
                        .HasForeignKey("IDProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.LoaiSanPham", "ProductType")
                        .WithMany()
                        .HasForeignKey("IDProductType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("QRB.Models.SanPham", b =>
                {
                    b.HasOne("QRB.Models.Department", "ChiNhanh")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRB.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("QRB.Models.UserBranch", b =>
                {
                    b.HasOne("QRB.Models.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QRB.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QRB.Models.Voucher", b =>
                {
                    b.HasOne("QRB.Models.Customer", "Customer")
                        .WithMany("Vouchers")
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QRB.Models.Authorization.AppRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QRB.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("QRB.Models.DeXuatMuaSam", b =>
                {
                    b.Navigation("ChiTietDonDeXuats");
                });

            modelBuilder.Entity("QRB.Models.Department", b =>
                {
                    b.Navigation("DeXuatMuaSams");

                    b.Navigation("DonHangs");

                    b.Navigation("KhoSanPhams");

                    b.Navigation("LoaiSanPhams");

                    b.Navigation("NguoiDungs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QRB.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("QRB.Models.Ingredient", b =>
                {
                    b.Navigation("KhoSanPhams");
                });

            modelBuilder.Entity("QRB.Models.LoaiSanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("QRB.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("QRB.Models.NguyenLieu", b =>
                {
                    b.Navigation("KhoSanPhams");
                });

            modelBuilder.Entity("QRB.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("QRB.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LoaiSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
